language: c
addons:
  apt:
    packages:
      - cmake
    sources:
      - kubuntu-backports
matrix:
    include:
        - os: linux
          env:  NDK_VERSION=r10e BUILD_SCRIPT=build_android.sh 
        - os: osx
          env: BUILD_SCRIPT=build_iphone.sh
before_script:
  - if [ -n "$NDK_VERSION" ]; then git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root && export NDK_ROOT=$HOME/android-ndk-root
script:
  - mkdir build && cd build && cmake .. && cmake --build .
  - $TRAVIS_BUILD_DIR/$BUILD_SCRIPT
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    tags: true
